
in:
  type: file
  path_prefix: ./example/data.tsv
  parser:
    type: csv
    delimiter: "\t"
    skip_header_lines: 0
    null_string: ""
    columns:
      - { name: id, type: long }
      - { name: description, type: string }
      - { name: name, type: string }
      - { name: t, type: timestamp, format: "%Y-%m-%d %H:%M:%S %z"}
      - { name: payload, type: json}
    stop_on_invalid_record: true

out:
  type: s3_parquet
  bucket: example
  region: us-east-1
  endpoint: http://127.0.0.1:4572
  path_prefix: path/to/my-obj.
  file_ext: snappy.parquet
  compression_codec: snappy
  default_timezone: Asia/Tokyo
  canned_acl: bucket-owner-full-control
