version: 2
jobs:
  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install docker openjdk-8-jdk
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test

workflows:
  version: 2

  test:
    jobs:
      - test
