name: Test CI

on:
  - push

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: scalafmt
      run: ./gradlew spotlessCheck
    - name: scalatest
      run: ./gradlew scalatest

